import { Shield, Lock, Eye, FileText, Users, Phone } from "lucide-react";
import Link from "next/link";

export default function PrivacyPage() {
  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-blue-50 to-white py-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
              Privacy Policy
            </h1>
            <p className="text-xl text-gray-600 max-w-3xl mx-auto">
              Your privacy is important to us. Learn how we protect your health information.
            </p>
          </div>
        </div>
      </section>

      {/* Main Content */}
      <section className="py-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* HIPAA Notice */}
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-8 mb-12">
            <div className="flex items-start">
              <Shield className="h-8 w-8 text-blue-600 mr-4 flex-shrink-0 mt-1" />
              <div>
                <h2 className="text-2xl font-bold text-gray-900 mb-4">HIPAA Notice of Privacy Practices</h2>
                <p className="text-gray-700 leading-relaxed">
                  This notice describes how medical information about you may be used and disclosed and how 
                  you can get access to this information. Please review it carefully. The privacy of your 
                  health information is important to us.
                </p>
              </div>
            </div>
          </div>

          {/* Our Commitment */}
          <div className="bg-white rounded-lg shadow-lg p-8 mb-12">
            <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center">
              <Lock className="h-6 w-6 text-blue-600 mr-3" />
              Our Commitment to Privacy
            </h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              Scruggs Podiatry PC is committed to maintaining the privacy and confidentiality of your personal 
              health information. We understand that your medical information is personal and we are committed 
              to protecting it.
            </p>
            <p className="text-gray-700 leading-relaxed">
              This notice applies to all records of your care generated by this practice, whether made by our 
              practice personnel or your personal doctor. This notice will tell you about the ways in which we 
              may use and disclose health information about you.
            </p>
          </div>

          {/* How We Use Information */}
          <div className="mb-12">
            <h2 className="text-2xl font-bold text-gray-900 mb-6">How We May Use and Disclose Health Information</h2>
            
            <div className="space-y-6">
              <div className="bg-gray-50 rounded-lg p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center">
                  <FileText className="h-5 w-5 text-green-600 mr-2" />
                  For Treatment
                </h3>
                <p className="text-gray-700">
                  We may use your health information to provide you with medical treatment or services. We may 
                  disclose medical information about you to doctors, nurses, technicians, or other personnel 
                  who are involved in taking care of you.
                </p>
              </div>

              <div className="bg-gray-50 rounded-lg p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center">
                  <Users className="h-5 w-5 text-blue-600 mr-2" />
                  For Payment
                </h3>
                <p className="text-gray-700">
                  We may use and disclose your health information so that the treatment and services you receive 
                  may be billed to and payment may be collected from you, an insurance company, or a third party.
                </p>
              </div>

              <div className="bg-gray-50 rounded-lg p-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-3 flex items-center">
                  <Eye className="h-5 w-5 text-purple-600 mr-2" />
                  For Healthcare Operations
                </h3>
                <p className="text-gray-700">
                  We may use and disclose your health information for our practice operations. These uses and 
                  disclosures are necessary to run our practice and make sure our patients receive quality care.
                </p>
              </div>
            </div>
          </div>

          {/* Your Rights */}
          <div className="bg-white rounded-lg shadow-lg p-8 mb-12">
            <h2 className="text-2xl font-bold text-gray-900 mb-6">Your Rights Regarding Health Information</h2>
            <p className="text-gray-700 mb-6">
              You have the following rights regarding health information we maintain about you:
            </p>
            <ul className="space-y-4">
              <li className="flex items-start">
                <span className="text-green-600 mr-3 mt-1">✓</span>
                <div>
                  <strong className="text-gray-900">Right to Inspect and Copy:</strong>
                  <p className="text-gray-700 mt-1">
                    You have the right to inspect and copy your health information that may be used to make 
                    decisions about your care.
                  </p>
                </div>
              </li>
              <li className="flex items-start">
                <span className="text-green-600 mr-3 mt-1">✓</span>
                <div>
                  <strong className="text-gray-900">Right to Amend:</strong>
                  <p className="text-gray-700 mt-1">
                    If you feel that health information we have is incorrect or incomplete, you may ask us 
                    to amend the information.
                  </p>
                </div>
              </li>
              <li className="flex items-start">
                <span className="text-green-600 mr-3 mt-1">✓</span>
                <div>
                  <strong className="text-gray-900">Right to an Accounting of Disclosures:</strong>
                  <p className="text-gray-700 mt-1">
                    You have the right to request a list of certain disclosures we made of your health information.
                  </p>
                </div>
              </li>
              <li className="flex items-start">
                <span className="text-green-600 mr-3 mt-1">✓</span>
                <div>
                  <strong className="text-gray-900">Right to Request Restrictions:</strong>
                  <p className="text-gray-700 mt-1">
                    You have the right to request a restriction or limitation on the health information we use 
                    or disclose for treatment, payment, or health care operations.
                  </p>
                </div>
              </li>
              <li className="flex items-start">
                <span className="text-green-600 mr-3 mt-1">✓</span>
                <div>
                  <strong className="text-gray-900">Right to Request Confidential Communications:</strong>
                  <p className="text-gray-700 mt-1">
                    You have the right to request that we communicate with you about medical matters in a 
                    certain way or at a certain location.
                  </p>
                </div>
              </li>
            </ul>
          </div>

          {/* Security Measures */}
          <div className="bg-gray-50 rounded-lg p-8 mb-12">
            <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center">
              <Shield className="h-6 w-6 text-blue-600 mr-3" />
              Our Security Measures
            </h2>
            <p className="text-gray-700 mb-4">
              We maintain appropriate physical, electronic, and procedural safeguards to protect your health 
              information, including:
            </p>
            <ul className="space-y-2 text-gray-700">
              <li className="flex items-start">
                <span className="text-blue-600 mr-2">•</span>
                Secure storage of physical records
              </li>
              <li className="flex items-start">
                <span className="text-blue-600 mr-2">•</span>
                Password-protected electronic systems
              </li>
              <li className="flex items-start">
                <span className="text-blue-600 mr-2">•</span>
                Limited access to health information
              </li>
              <li className="flex items-start">
                <span className="text-blue-600 mr-2">•</span>
                Staff training on privacy procedures
              </li>
              <li className="flex items-start">
                <span className="text-blue-600 mr-2">•</span>
                Regular security assessments
              </li>
            </ul>
          </div>

          {/* Contact Information */}
          <div className="bg-blue-600 text-white rounded-lg p-8">
            <h2 className="text-2xl font-bold mb-4 flex items-center">
              <Phone className="h-6 w-6 mr-3" />
              Questions or Complaints
            </h2>
            <p className="text-blue-100 mb-6">
              If you believe your privacy rights have been violated or you have questions about our privacy 
              practices, you may contact us at:
            </p>
            <div className="bg-white/10 rounded-lg p-4 mb-6">
              <p className="font-semibold">Privacy Officer</p>
              <p>Scruggs Podiatry PC</p>
              <p>19 Walker Avenue, Suite 200</p>
              <p>Pikesville, MD 21208</p>
              <p className="mt-2">
                Phone: <a href="tel:4104865454" className="underline">(410) 486-5454</a>
              </p>
            </div>
            <p className="text-blue-100 text-sm">
              You also have the right to file a complaint with the Secretary of the Department of Health and 
              Human Services. We will not retaliate against you for filing a complaint.
            </p>
          </div>

          {/* Effective Date */}
          <div className="mt-8 text-center text-gray-600">
            <p className="text-sm">
              This notice is effective as of January 1, 2024 and will remain in effect until replaced.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
